  services:

    clients-service:
      build: clients-service
      hostname: clients-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        mysql1:
          condition: service_healthy

    products-service:
      build: products-service
      hostname: products-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        mysql2:
          condition: service_healthy

    checkout-service:
      build: checkout-service
      hostname: checkout-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        mysql3:
          condition: service_healthy

    delivery-service:
      build: delivery-service
      hostname: delivery-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        mysql4:
          condition: service_healthy



    mysql1:
      image: mysql:5.7
      ports:
        - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=rootpwd
        - MYSQL_DATABASE=clients-db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
      volumes:
        - ./data/mysql1:/var/lib/mysql1
        - ./data/init.d:/docker-entrypoint-initdb.d
      healthcheck:
        test:
          [
            "CMD",
            "mysqladmin",
            "ping",
            "-uuser",
            "-ppwd",
            "-h",
            "localhost",
          ]
        interval: 10s
        timeout: 5s
        retries: 10



    mysql2:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=rootpwd
        - MYSQL_DATABASE=products-db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
      volumes:
        - ./data/mysql2:/var/lib/mysql2
        - ./data/init.d:/docker-entrypoint-initdb.d
      healthcheck:
        test:
          [
            "CMD",
            "mysqladmin",
            "ping",
            "-uuser",
            "-ppwd",
            "-h",
            "localhost",
          ]
        interval: 10s
        timeout: 5s
        retries: 10

    mysql3:
      image: mysql:5.7
      ports:
        - "3309:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=rootpwd
        - MYSQL_DATABASE=checkout-db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
      volumes:
        - ./data/mysql3:/var/lib/mysql3
        - ./data/init.d:/docker-entrypoint-initdb.d
      healthcheck:
        test:
          [
            "CMD",
            "mysqladmin",
            "ping",
            "-uuser",
            "-ppwd",
            "-h",
            "localhost",
          ]
        interval: 10s
        timeout: 5s
        retries: 10

    mysql4:
      image: mysql:5.7
      ports:
        - "3310:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=rootpwd
        - MYSQL_DATABASE=deliveries-db
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pwd
      volumes:
        - ./data/mysql4:/var/lib/mysql4
        - ./data/init.d:/docker-entrypoint-initdb.d
      healthcheck:
        test:
          [
            "CMD",
            "mysqladmin",
            "ping",
            "-uuser",
            "-ppwd",
            "-h",
            "localhost",
          ]
        interval: 10s
        timeout: 5s
        retries: 10
