# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.onlineperfumeshop: DEBUG
app:
  client-service:
    host: localhost
    port: 7001
  product-service:
    host: localhost
    port: 7002
  checkout-service:
    host: localhost
    port: 7003
  delivery-service:
    host: localhost
    port: 8080

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  client-service:
    host: client-service
    port: 8080
  checkout-service:
    host: checkout-service
    port: 8080
  product-service:
    host: product-service
    port: 8080
  delivery-service:
    host: delivery-service
    port: 8080
