# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.onlineperfumeshop: DEBUG

app:
  clients-service:
    host: localhost
    port: 7001
  checkout-service:
    host: localhost
    port: 7002
  products-service:
    host: localhost
    port: 7003
  delivery-service:
    host: localhost
    port: 7004

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  clients-service:
    host: clients-service
    port: 8080
  checkout-service:
    host: checkout-service
    port: 8080
  products-service:
    host: products-service
    port: 8080
  delivery-service:
    host: delivery-service
    port: 8080
